### ISSUE TITLE
Map Editor - Changing the alias doesn't actually save

### ISSUE THREAD

**Issue by asinck** [allejo/bzion#122] opened 2017-09-17 05:15 UTC

**Comment by allejo** [comment] 2017-09-17 08:33
Can you elaborate your steps on this one? Can't reproduce

**Comment by asinck** [comment] 2017-09-17 23:09
This may be related to #125  . I think I may be crossing up "alias" and the URL page.

For the Pizza map, I edited the alias of from '10' to something else, but going to http://sandbox.leaguesunited.org/maps/10 still gave the Pizza map, while the new alias didn't work.

**Comment by allejo** [comment] 2017-09-18 00:06
Closing this since it's directly related to #125

**Closed by allejo** 2017-09-18 00:06 UTC
Labels: back-end, bug
